# -*- coding: utf-8 -*-
"""coinbase_data_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmtgqTIzJsn92Ux27tFqiU89AqXuVLpb
"""

import requests
import pandas as pd
from datetime import datetime,timedelta

url0 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2022-03-17&end=2022-04-25&granularity=86400"
headers = {"Accept": "application/json"}

data0 = requests.request("GET", url0, headers=headers).json()

url1 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2021-05-22&end=2022-03-16&granularity=86400"
headers = {"Accept": "application/json"}

data1 = requests.request("GET", url1, headers=headers).json()

url2 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2020-07-26&end=2021-05-21&granularity=86400"
headers = {"Accept": "application/json"}

data2 = requests.request("GET", url2, headers=headers).json()

url3 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2019-09-30&end=2020-07-25&granularity=86400"
headers = {"Accept": "application/json"}

data3 = requests.request("GET", url3, headers=headers).json()

url4 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2018-12-04&end=2019-09-29&granularity=86400"
headers = {"Accept": "application/json"}

data4 = requests.request("GET", url4, headers=headers).json()

url5 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2018-02-07&end=2018-12-03&granularity=86400"
headers = {"Accept": "application/json"}

data5 = requests.request("GET", url5, headers=headers).json()

url6 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2017-04-13&end=2018-02-06&granularity=86400"
headers = {"Accept": "application/json"}

data6 = requests.request("GET", url6, headers=headers).json()

# finding start date:
'''
EndDate = "04/12/17"
Date = datetime.strptime(EndDate, "%m/%d/%y")
StartDate = Date-timedelta(days=300)
print(StartDate)
'''

url7 = "https://api.pro.coinbase.com/products/BTC-USD/candles?start=2016-06-17T00:00:00&end=2017-04-12&granularity=86400"
headers = {"Accept": "application/json"}

data7 = requests.request("GET", url7, headers=headers).json()

total = []
total.extend(data0)
total.extend(data1)
total.extend(data2)
total.extend(data3)
total.extend(data4)
total.extend(data5)
total.extend(data6)
total.extend(data7)

df = pd.DataFrame(total,
                  columns = ["time","Low","High","Open","Close","Volume"])

df["timestamp"] = pd.to_datetime(df["time"] , unit = 's')
df = df[["timestamp" , "Low" ,"High" ,"Open","Close","Volume"]]

#print(df)

df.to_excel('coinbase_Dataset.xlsx', encoding='utf-8', index=False)

"""# New Section"""